#!/bin/zsh -e

function set-param () {
  local key=$1
	local val=$2
	sed -Ei "s/#define ${key}.*/#define ${key} ${val}/" \
		roce_for_disagg/roce_disagg.h
}

function set-queues () {
	local cnqp=$1
	local fhqp=$2
	local cn_txd=$3
	local fh_txd=$4
	local max_txd=$((cn_txd > fh_txd ? cn_txd : fh_txd))

	set-param MIND_RDMA_MAX_NUM_FHQP 64
	set-param MIND_RDMA_MAX_NUM_CNQP 16
	set-param MIND_RDMA_MAX_QP_TRANSMISSION_DEPTH $max_txd

	set-param MIND_RDMA_FHQP_TRANSMISSION_DEPTH $fh_txd
	set-param MIND_RDMA_FHQP_SIZE               $fh_txd
	set-param MIND_RDMA_FHCQ_SIZE               $(( fh_txd * fhqp ))
	set-param MIND_RDMA_FHCQ_POLL_BATCH_SIZE    16

	set-param MIND_RDMA_CNQP_TRANSMISSION_DEPTH $cn_txd
	set-param MIND_RDMA_CNQP_SIZE               $cn_txd
	set-param MIND_RDMA_CNCQ_SIZE               $(( cn_txd * cnqp ))
	set-param MIND_RDMA_CNCQ_POLL_BATCH_SIZE    16

	chronic make clean
	chronic make
}

rm -rf logs

mkdir -p class1-quicksweep

local cn=0
local fh=1
local cn_qp=0
local fh_txd=1
local cn_txd=16
for fh_qp in 1 2 $(seq 4 4 64); do
	set-queues $cn_qp $fh_qp $cn_txd $fh_txd
	./test-one.zsh $cn $fh $cn_qp $fh_qp
	sleep 5
done

mv logs class1-quicksweep
