#!/bin/zsh

if [[ -z $MIND_ROOT ]]; then
	echo '$MIND_ROOT not set!' >/dev/stderr
	exit 1
fi
source $MIND_ROOT/scripts/config.sh
cd $MIND_ROOT/mem-server

echo "$HOST: rebuilding mem server (no output => success)"
make clean_rdma_server
