#ifndef __CLUSTER_DISAGGREGATION_H__
#define __CLUSTER_DISAGGREGATION_H__

#define DISAGG_MEMORY_NODE_ID   1
#define DISAGG_CONTROLLER_NODE_ID 0
#define DISAGG_CONTROLLER_PID_NS 0

#define DISAGG_COMPUTE_NODE_IP_START 205
#define DISAGG_MEMORY_NODE_IP_START 206

#endif
