#!/bin/zsh -e

key=$1
val=$2

if [[ -z $MIND_ROOT ]]; then
        echo '$MIND_ROOT not set!' >/dev/stderr
        exit 1
fi
source $MIND_ROOT/scripts/config.sh
cd $MIND_ROOT

sed -Ei "s/#define ${key}.*/#define ${key} ${val}/" \
	    $MIND_ROOT/mind_linux/include/disagg/cnthread_disagg.h
