/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MindUser.h"
#include "MindUser.tcc"




MindUser_run_command_args::~MindUser_run_command_args() noexcept {
}


MindUser_run_command_pargs::~MindUser_run_command_pargs() noexcept {
}


MindUser_run_command_result::~MindUser_run_command_result() noexcept {
}


MindUser_run_command_presult::~MindUser_run_command_presult() noexcept {
}



